In [1]:
import numpy as np
import pandas as pd
import datetime as dt

In [45]:
df = pd.read_csv('order_brush_order.csv')
df.describe()

            orderid        shopid        userid
count  2.227500e+05  2.227500e+05  2.227500e+05
mean   3.130027e+13  9.433117e+07  9.802880e+07
std    1.222774e+11  5.695790e+07  6.839048e+07
min    3.107520e+13  1.000900e+04  1.000700e+04
25%    3.120360e+13  4.980267e+07  3.508127e+07
50%    3.130561e+13  9.033636e+07  9.309625e+07
75%    3.140604e+13  1.475053e+08  1.590612e+08
max    3.150720e+13  2.154352e+08  2.155262e+08

In [46]:
df.head()

          orderid     shopid     userid           event_time
0  31076582227611   93950878   30530270  2019-12-27 00:23:03
1  31118059853484  156423439   46057927  2019-12-27 11:54:20
2  31123355095755  173699291   67341739  2019-12-27 13:22:35
3  31122059872723   63674025  149380322  2019-12-27 13:01:00
4  31117075665123  127249066  149493217  2019-12-27 11:37:55

In [47]:
# convert the 'Date' column to datetime format 
df['event_time']= pd.to_datetime(df['event_time']) 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 222750 entries, 0 to 222749
Data columns (total 4 columns):
orderid       222750 non-null int64
shopid        222750 non-null int64
userid        222750 non-null int64
event_time    222750 non-null datetime64[ns]
dtypes: datetime64[ns](1), int64(3)
memory usage: 6.8 MB

In [21]:
day = df['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = df['event_time'][i].day

day1.head()

0    27
1    27
2    27
3    27
4    27
dtype: int64

In [23]:
hour = df['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    hour1[i] = df['event_time'][i].hour

hour1.head()

0     0
1    11
2    13
3    13
4    11
dtype: int64

In [30]:
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
hour2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 222750 entries, 0 to 222749
Data columns (total 1 columns):
Hour    222750 non-null int64
dtypes: int64(1)
memory usage: 1.7 MB

In [31]:
df['Day']= day2['Day']
df['Hour']=hour2['Hour']
df.head()

          orderid     shopid     userid          event_time  Day  Hour
0  31076582227611   93950878   30530270 2019-12-27 00:23:03   27     0
1  31118059853484  156423439   46057927 2019-12-27 11:54:20   27    11
2  31123355095755  173699291   67341739 2019-12-27 13:22:35   27    13
3  31122059872723   63674025  149380322 2019-12-27 13:01:00   27    13
4  31117075665123  127249066  149493217 2019-12-27 11:37:55   27    11

In [32]:
df2 = df[['shopid','userid','Day','Hour']]
df2.head()

      shopid     userid  Day  Hour
0   93950878   30530270   27     0
1  156423439   46057927   27    11
2  173699291   67341739   27    13
3   63674025  149380322   27    13
4  127249066  149493217   27    11

In [39]:
#df2.groupby(['shopid','userid','Day','Hour']).count()

dsum = df2.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
dsum
#dsum.to_csv (r'export_dataframe3.csv', index = False, header=True)

shopid     userid     Day  Hour
10009      196962305  27   3       1
10051      2854032    27   19      1
           48600461   29   1       1
10061      62464559   31   2       1
           130633421  30   21      1
                                  ..
214949521  46269178   31   20      1
214964814  200983383  29   22      1
215175775  13688804   31   9       1
           129266028  31   14      1
215435223  79515106   31   18      1
Name: Hour, Length: 215877, dtype: int64

In [40]:
dsum1=pd.DataFrame(dsum)
dsum1.head()

                           Hour
shopid userid    Day Hour
10009  196962305 27  3        1
10051  2854032   27  19       1
       48600461  29  1        1
10061  62464559  31  2        1
       130633421 30  21       1

In [43]:
dsum1.to_csv (r'export_dataframe3.csv', index = True, header=True)

In [104]:
# Read csv file original
brush = pd.read_csv('order_brush_order.csv')

# convert the 'Date' column to datetime format 
brush['event_time']= pd.to_datetime(brush['event_time']) 

# Final 0
dsum1.head()

# Dataset 1 min 1
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final1 = pd.DataFrame(grouped)

# Dataset 1 min 2
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final2 = pd.DataFrame(grouped)

# Dataset 1 min 3
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final3 = pd.DataFrame(grouped)

# Dataset 1 min 4
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final4 = pd.DataFrame(grouped)

# Dataset 1 min 5
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final5 = pd.DataFrame(grouped)

# Dataset 1 min 6
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final6 = pd.DataFrame(grouped)

# Dataset 1 min 7
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final7 = pd.DataFrame(grouped)

# Dataset 1 min 8
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final8 = pd.DataFrame(grouped)

# Dataset 1 min 9
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final9 = pd.DataFrame(grouped)

# Dataset 1 min 10
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final10 = pd.DataFrame(grouped)

In [105]:
# Dataset 1 min 11
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final11 = pd.DataFrame(grouped)

# Dataset 1 min 12
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final12 = pd.DataFrame(grouped)

# Dataset 1 min 13
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final13 = pd.DataFrame(grouped)

# Dataset 1 min 14
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final14 = pd.DataFrame(grouped)

# Dataset 1 min 15
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final15 = pd.DataFrame(grouped)

# Dataset 1 min 16
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final16 = pd.DataFrame(grouped)

# Dataset 1 min 17
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final17 = pd.DataFrame(grouped)

# Dataset 1 min 18
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final18 = pd.DataFrame(grouped)

# Dataset 1 min 19
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final19 = pd.DataFrame(grouped)

# Dataset 1 min 20
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final20 = pd.DataFrame(grouped)

In [106]:
# Dataset 1 min 21
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final21 = pd.DataFrame(grouped)

# Dataset 1 min 22
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final22 = pd.DataFrame(grouped)

# Dataset 1 min 23
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final23 = pd.DataFrame(grouped)

# Dataset 1 min 24
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final24 = pd.DataFrame(grouped)

# Dataset 1 min 25
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final25 = pd.DataFrame(grouped)

# Dataset 1 min 26
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final26 = pd.DataFrame(grouped)

# Dataset 1 min 27
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final27 = pd.DataFrame(grouped)

# Dataset 1 min 28
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final28 = pd.DataFrame(grouped)

# Dataset 1 min 29
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final29 = pd.DataFrame(grouped)

# Dataset 1 min 30
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final30 = pd.DataFrame(grouped)

In [107]:
# Dataset 1 min 31
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final31 = pd.DataFrame(grouped)

# Dataset 1 min 32
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final32 = pd.DataFrame(grouped)

# Dataset 1 min 33
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final33 = pd.DataFrame(grouped)

# Dataset 1 min 34
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final34 = pd.DataFrame(grouped)

# Dataset 1 min 35
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final35 = pd.DataFrame(grouped)

# Dataset 1 min 36
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final36 = pd.DataFrame(grouped)

# Dataset 1 min 37
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final37 = pd.DataFrame(grouped)

# Dataset 1 min 38
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final38 = pd.DataFrame(grouped)

# Dataset 1 min 39
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final39 = pd.DataFrame(grouped)

# Dataset 1 min 40
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final40 = pd.DataFrame(grouped)

In [108]:
# Dataset 1 min 41
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final41 = pd.DataFrame(grouped)

# Dataset 1 min 42
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final42 = pd.DataFrame(grouped)

# Dataset 1 min 43
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final43 = pd.DataFrame(grouped)

# Dataset 1 min 44
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final44 = pd.DataFrame(grouped)

# Dataset 1 min 45
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final45 = pd.DataFrame(grouped)

# Dataset 1 min 46
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final46 = pd.DataFrame(grouped)

# Dataset 1 min 47
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final47 = pd.DataFrame(grouped)

# Dataset 1 min 48
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final48 = pd.DataFrame(grouped)

# Dataset 1 min 49
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final49 = pd.DataFrame(grouped)

# Dataset 1 min 50
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final50 = pd.DataFrame(grouped)

In [109]:
# Dataset 1 min 51
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final51 = pd.DataFrame(grouped)

# Dataset 1 min 52
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final52 = pd.DataFrame(grouped)

# Dataset 1 min 53
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final53 = pd.DataFrame(grouped)

# Dataset 1 min 54
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final54 = pd.DataFrame(grouped)

# Dataset 1 min 55
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final55 = pd.DataFrame(grouped)

# Dataset 1 min 56
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final56 = pd.DataFrame(grouped)

# Dataset 1 min 57
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final57 = pd.DataFrame(grouped)

# Dataset 1 min 58
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final58 = pd.DataFrame(grouped)

# Dataset 1 min 59
brush['event_time']= brush['event_time'] - dt.timedelta(minutes=1)
brush.head()
data1 = brush

# Extract Day & Hour
day = brush['shopid']
day1 = day.rename(columns={'shopid': 'Day'})
hour = brush['shopid']
hour1 = hour.rename(columns={'shopid': 'Day'})
for i in range(222750):
    day1[i] = brush['event_time'][i].day
    hour1[i] = brush['event_time'][i].hour
    
# Add Column name for Day & Hour, merge to Dataset 1
day2=pd.DataFrame(day1, columns=['Day'])
hour2=pd.DataFrame(hour1, columns=['Hour'])
data1['Day']= day2['Day']
data1['Hour']=hour2['Hour']

# Calculate Concentrate rate
dataf1 = data1[['shopid','userid','Day','Hour']]
grouped = dataf1.groupby(['shopid','userid','Day','Hour'])['Hour'].count()
final59 = pd.DataFrame(grouped)

In [111]:
frames = [dsum1, final1, final2, final3, final4, final5, final6, final7, final8, final9, final10,
          final11, final12, final13, final14, final15, final16, final17, final18, final19, final20,
          final21, final22, final23, final24, final25, final26, final27, final28, final29, final30,
          final31, final32, final33, final34, final35, final36, final37, final38, final39, final40,
          final41, final42, final43, final44, final45, final46, final47, final48, final49, final50,
          final51, final52, final53, final54, final55, final56, final57, final58, final59]
result = pd.concat(frames)
result.columns

Index(['Hour'], dtype='object')

In [112]:
result = result[result['Hour'] >=3]
result

                              Hour
shopid    userid    Day Hour
10159     214988798 29  20       3
10287     198097381 30  0        3
          214226569 31  1        3
10402     77819     28  14       3
10536     672345    27  11       3
...                            ...
203531250 114282846 29  16       3
204225676 198662175 30  23       5
208696908 214111334 30  16       3
210197928 52867898  27  6        4
213141071 213646699 27  0        3

[45288 rows x 1 columns]

In [113]:
result.to_csv (r'export_dataframe4.csv', index = True, header=True)